
# Generated by CodiumAI
from school.alx-higher_level_programming.0x0A-python-inheritance.1-main import MyList


import pytest

class TestMyList:

    # Test that the print_sorted() method of MyList class correctly sorts and prints a list of integers
    def test_print_sorted_with_integers(self):
        my_list = MyList([4, 2, 1, 3])
        my_list.print_sorted()
        # Assert that the output is the sorted list
        assert my_list == [1, 2, 3, 4]

